/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnglePairsRouteImport } from './routes/angle-pairs'
import { Route as ParallelLinesRouteImport } from './routes/parallel-lines'
import { Route as ProofsRouteImport } from './routes/proofs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnglePairsRoute = AnglePairsRouteImport.update({
  id: '/angle-pairs',
  path: '/angle-pairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelLinesRoute = ParallelLinesRouteImport.update({
  id: '/parallel-lines',
  path: '/parallel-lines',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofsRoute = ProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angle-pairs': typeof AnglePairsRoute
  '/parallel-lines': typeof ParallelLinesRoute
  '/proofs': typeof ProofsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angle-pairs': typeof AnglePairsRoute
  '/parallel-lines': typeof ParallelLinesRoute
  '/proofs': typeof ProofsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angle-pairs': typeof AnglePairsRoute
  '/parallel-lines': typeof ParallelLinesRoute
  '/proofs': typeof ProofsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/angle-pairs' | '/parallel-lines' | '/proofs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/angle-pairs' | '/parallel-lines' | '/proofs'
  id: '__root__' | '/' | '/angle-pairs' | '/parallel-lines' | '/proofs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnglePairsRoute: typeof AnglePairsRoute
  ParallelLinesRoute: typeof ParallelLinesRoute
  ProofsRoute: typeof ProofsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angle-pairs': {
      id: '/angle-pairs'
      path: '/angle-pairs'
      fullPath: '/angle-pairs'
      preLoaderRoute: typeof AnglePairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-lines': {
      id: '/parallel-lines'
      path: '/parallel-lines'
      fullPath: '/parallel-lines'
      preLoaderRoute: typeof ParallelLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proofs': {
      id: '/proofs'
      path: '/proofs'
      fullPath: '/proofs'
      preLoaderRoute: typeof ProofsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnglePairsRoute: AnglePairsRoute,
  ParallelLinesRoute: ParallelLinesRoute,
  ProofsRoute: ProofsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
